### ISSUE TITLE
METIS problems

### ISSUE THREAD

**Issue by zerothi** [symPACK/symPACK#3]
Hi again ;)

I have problems building with METIS, and this time I checked CMake files etc. but can't figure out where the command line is build!

```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_LIBRARY=' -L/opt/gnu/8.3.0/metis/5.1.0/lib -Wl,-rpath=/opt/gnu/8.3.0/metis/5.1.0/lib -lmetis' -DENABLE_METIS=ON -DMETIS_INCLUDE_DIR='/opt/gnu/8.3.0/metis/5.1.0/include' -DPARMETIS_LIBRARY=' -L/opt/gnu/8.3.0/parmetis/4.0.3/lib -Wl,-rpath=/opt/gnu/8.3.0/parmetis/4.0.3/lib -lparmetis -lmetis' -DENABLE_PARMETIS=ON -DPARMETIS_INCLUDE_DIR='/opt/gnu/8.3.0/parmetis/4.0.3/include' -DSCOTCH_LIBRARY=' -L/opt/gnu/8.3.0/scotch/6.0.4/lib -Wl,-rpath=/opt/gnu/8.3.0/scotch/6.0.4/lib -lscotch -lscotcherr -lscotcherrexit' -DENABLE_SCOTCH=ON -DSCOTCH_INCLUDE_DIR='/opt/gnu/8.3.0/scotch/6.0.4/include' -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' -DLAPACK_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' ..
```
However it fails with this error message:
```bash
CMake Error at /opt/generic/build-tools/1.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find METIS (missing: METIS_TEST_RUNS)
Call Stack (most recent call first):
  /opt/generic/build-tools/1.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMETIS.cmake:116 (find_package_handle_standard_args)
  CMakeLists.txt:177 (find_package)
```

I looked into `FindMETIS.cmake` and found that only `METIS_LIBRARY` and `METIS_INCLUDE_DIR` should be needed to be defined. However, the actual error message in the `CMakeError.log` gives this:
```bash
/opt/generic/gcc/8.3.0/bin/gcc   -O3 -DNDEBUG  -Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread;-Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread  CMakeFiles/cmTC_aa406.dir/CheckIncludeFile.c.o  -o cmTC_aa406 
```
I have no clue as to how `-pthread;-Wl,-rpath` gets mixed up in this case! Do you have any suggestions?

**Comment by mjacquel** [comment]
Nick,

From my experience, the best way to get CMake to find METIS is to use
METIS_PREFIX, which should point to a Metis installation directory (the one
containing include lib subfolders).

So -DMETIS_PREFIX=path -DENABLE_METIS=ON

Best,

Mathias Jacquelin
Research Scientist
Lawrence Berkeley National Laboratory
mjacquelin@lbl.gov
1-510-495-2605

**Comment by zerothi** [comment]
Yeah sorry, I had already tried that:
```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_PREFIX='/opt/gnu/8.3.0/metis/5.1.0' -DENABLE_METIS=ON -DPARMETIS_LIBRARY=' -L/opt/gnu/8.3.0/parmetis/4.0.3/lib -Wl,-rpath=/opt/gnu/8.3.0/parmetis/4.0.3/lib -lparmetis -lmetis' -DENABLE_PARMETIS=ON -DPARMETIS_INCLUDE_DIR='/opt/gnu/8.3.0/parmetis/4.0.3/include' -DSCOTCH_LIBRARY=' -L/opt/gnu/8.3.0/scotch/6.0.4/lib -Wl,-rpath=/opt/gnu/8.3.0/scotch/6.0.4/lib -lscotch -lscotcherr -lscotcherrexit' -DENABLE_SCOTCH=ON -DSCOTCH_INCLUDE_DIR='/opt/gnu/8.3.0/scotch/6.0.4/include' -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' -DLAPACK_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' ..
```
and the resulting output:
```bash
Linking C executable cmTC_54db2
/opt/generic/build-tools/1.0/bin/cmake -E cmake_link_script CMakeFiles/cmTC_54db2.dir/link.txt --verbose=1
/opt/generic/gcc/8.3.0/bin/gcc   -O3 -DNDEBUG  -Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread;-Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread  CMakeFiles/cmTC_54db2.dir/CheckIncludeFile.c.o  -o cmTC_54db2 
gcc: error: unrecognized command line option ‘-pthread;-Wl,-rpath’
make[1]: *** [CMakeFiles/cmTC_54db2.dir/build.make:87: cmTC_54db2] Error 1
```
are there special CMake versions that are incompatible or something? I was running with Cmake 3.13.2, I will now try with 3.14.1 (latest).

**Comment by mjacquel** [comment]
CMake 3.13 should be working.

Could you try not enabling PARMETIS first? I think it would make things
easier until we figure out how to use METIS.
What is the content of "/opt/gnu/8.3.0/metis/5.1.0" ?

Best,

Mathias Jacquelin
Research Scientist
Lawrence Berkeley National Laboratory
mjacquelin@lbl.gov
1-510-495-2605

**Comment by zerothi** [comment]
1. Content of folder:
```bash
$> ll /opt/gnu/8.3.0/metis/5.1.0
total 96K
drwxr-xr-x 1 nicpa nicpa   92 Mar 28 12:29 bin
-rw-r--r-- 1 nicpa nicpa 2.9K Mar 28 12:29 CMakeCache.txt.gz
-rw-r--r-- 1 nicpa nicpa  92K Mar 28 12:29 CMakeOutput.log
drwxr-xr-x 1 nicpa nicpa   14 Mar 28 12:29 include
drwxr-xr-x 1 nicpa nicpa   20 Mar 28 12:29 lib
```
Note that all my installations work with many other packages (Siesta, superlu-dist, scotch, MUMPS, getFEM). Again, it has nothing to do with METIS, it is because CMake creates a wrong compilation line.

2. Without ParMetis
```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_PREFIX='/opt/gnu/8.3.0/metis/5.1.0' -DENABLE_METIS=ON -DSCOTCH_LIBRARY=' -L/opt/gnu/8.3.0/scotch/6.0.4/lib -Wl,-rpath=/opt/gnu/8.3.0/scotch/6.0.4/lib -lscotch -lscotcherr -lscotcherrexit' -DENABLE_SCOTCH=ON -DSCOTCH_INCLUDE_DIR='/opt/gnu/8.3.0/scotch/6.0.4/include' -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' -DLAPACK_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' ..
```
same error

3. Without ParMETIS and without Scotch
```bash
cmake -DCMAKE_INSTALL_PREFIX=/opt/gnu/8.3.0/sympack/1.1 -DMETIS_PREFIX='/opt/gnu/8.3.0/metis/5.1.0' -DENABLE_METIS=ON -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' -DLAPACK_LIBRARIES=' -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas' ..
```

Same problem occurs, the testing linker line has:
```
gcc: error: unrecognized command line option ‘-pthread;-Wl,-rpath’
```
which obviously fails...

I am generally against CMake because it is extremely difficult to debug once something fails :(
Note that I am successfully using the cmake to build gromacs, lammps, eigen, opencoarrays, doxygen + others. So cmake shouldn't be that broken ;)

**Comment by mjacquel** [comment]
I am honestly thinking it is more an issue on my end ;-) The only file in
which pthread is mentioned is gasnet.cmake (in the cmake folder).
One thing to try is to edit the CmakeFiles/run_sympack.dir/link.txt (if
this is what you are trying to make) and remove any reference to lpthread
in there.


Best,

Mathias Jacquelin
Research Scientist
Lawrence Berkeley National Laboratory
mjacquelin@lbl.gov
1-510-495-2605

**Comment by zerothi** [comment]
Hi, sorry I went to bed ;)

I did `grep pthread **/*txt` in the sympack directory and found:
```bash
build-tmp/CMakeCache.txt:MPI_CXX_COMPILE_OPTIONS:STRING=-pthread
build-tmp/CMakeCache.txt:MPI_CXX_LINK_FLAGS:STRING=-Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread
build-tmp/CMakeCache.txt:MPI_C_COMPILE_OPTIONS:STRING=-pthread
build-tmp/CMakeCache.txt:MPI_C_LINK_FLAGS:STRING=-Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread
build-tmp/CMakeCache.txt:MPI_Fortran_COMPILE_OPTIONS:STRING=-pthread
build-tmp/CMakeCache.txt:MPI_Fortran_LINK_FLAGS:STRING=-Wl,-rpath -Wl,/opt/gnu/8.3.0/hwloc/2.0.3/lib -Wl,-rpath -Wl,/opt/gnu/8.3.0/openmpi/4.0.1/lib -Wl,--enable-new-dtags -L/opt/gnu/8.3.0/hwloc/2.0.3/lib -pthread
build-tmp/CMakeCache.txt://Have include pthread.h
```
there is no where an erroneous linker line?

Also, the file you mention, `CmakeFiles/run_sympack.dir/link.txt` does not exist?

**Comment by zerothi** [comment]
@mjacquel I still have a problem with threads, if I can supply any additional details, please let me know. :)

**Comment by zerothi** [comment]
I can successfully install 2.0.1 :)
